name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Create google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES }}' > app/google-services.json

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      # Sign APK and create release for tags

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'skincanorg/skincan'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'skincanorg/skincan'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'skincanorg/skincan'
        run: |
          set -e

          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk skincan-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum skincan-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk skincan-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum skincan-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk skincan-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum skincan-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk skincan-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum skincan-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk skincan-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum skincan-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'skincanorg/skincan'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: SkinCan ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }}
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
          files: |
            skincan-${{ env.VERSION_TAG }}.apk
            skincan-arm64-v8a-${{ env.VERSION_TAG }}.apk
            skincan-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            skincan-x86-${{ env.VERSION_TAG }}.apk
            skincan-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
